version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic" # Versions up to 1.3 not support Java 8
        versions: [">=1.4.0"]
      - dependency-name: "org.mockito:mockito-core" # Versions up to 5 not support Java 8
        versions: [ ">=5.0" ]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20
